/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Text: THREE.Mesh
  }
}

export function AboutMe(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/objects/texts/about-me.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-1.46, 0.05, -0.02]}
      />
    </group>
  )
}

useGLTF.preload('/objects/texts/about-me.glb')
