/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube011: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
}

export function Book(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/objects/book.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.002']}
        position={[0.32, -0.07, -5.35]}
        rotation={[-Math.PI / 2, 0.81, 0]}
        scale={[-2.49, -0.71, -0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials['Material.002']}
        position={[0.32, -0.07, 5.5]}
        rotation={[-Math.PI / 2, 0.81, -Math.PI]}
        scale={[-2.49, -0.71, -0.54]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.66, 0.25, -4.91]}
        rotation={[-Math.PI / 2, 0.81, 0]}
        scale={[-2.29, -0.66, -0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[0.66, 0.25, 5.07]}
        rotation={[-Math.PI / 2, 0.81, -Math.PI]}
        scale={[-2.29, -0.66, -0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials['Material.002']}
        position={[0.13, 1.85, -4.77]}
        rotation={[Math.PI / 2, -0.81, 0]}
        scale={[0.17, 0.38, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[0.97, 0.55, 5.07]}
        rotation={[-Math.PI / 2, 0.81, -Math.PI]}
        scale={[-2.29, -0.66, -0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[0.97, 0.55, -4.91]}
        rotation={[-Math.PI / 2, 0.81, 0]}
        scale={[-2.29, -0.66, -0.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials['Material.002']}
        position={[0.46, 1.51, -4.77]}
        rotation={[Math.PI / 2, -0.81, 0]}
        scale={[0.17, 0.38, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials['Material.002']}
        position={[0.81, 1.14, -4.77]}
        rotation={[Math.PI / 2, -0.81, 0]}
        scale={[0.17, 0.38, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials['Material.002']}
        position={[1.2, 0.73, -4.77]}
        rotation={[Math.PI / 2, -0.81, 0]}
        scale={[0.17, 0.38, 0.42]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials['Material.002']}
        position={[0.09, 1.84, 4.74]}
        rotation={[-Math.PI / 2, 0.81, -Math.PI]}
        scale={[-0.17, -0.25, -0.32]}
      />
    </group>
  )
}

useGLTF.preload('/objects/book.glb')
