/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import type * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Volume_button003: THREE.Mesh
    Screen_2: THREE.Mesh
    Key_Button001: THREE.Mesh
    Handphone001: THREE.Mesh
    Shape_Search: THREE.Mesh
    Shape_Search_2: THREE.Mesh
    Monitor: THREE.Mesh
    Screen: THREE.Mesh
    Shape_3: THREE.Mesh
    Shape: THREE.Mesh
    Shape_2: THREE.Mesh
    Line_5: THREE.Mesh
    Line_6: THREE.Mesh
    Shape_4: THREE.Mesh
    Shape_5: THREE.Mesh
    Sun: THREE.Mesh
    Mountain: THREE.Mesh
    Mountain_2: THREE.Mesh
    Sun_2: THREE.Mesh
    Mountain_3: THREE.Mesh
    Mountain_4: THREE.Mesh
    Play: THREE.Mesh
    Circle: THREE.Mesh
    Setting: THREE.Mesh
    Play_2: THREE.Mesh
    Circle_2: THREE.Mesh
    Setting_2: THREE.Mesh
    Line: THREE.Mesh
    Line_4: THREE.Mesh
    Monitor_Holder: THREE.Mesh
    Circle001: THREE.Mesh
    Circle002: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
}

export function MobileAndMonitor (props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/objects/mobile-monitor.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Volume_button003"
        castShadow
        receiveShadow
        geometry={nodes.Volume_button003.geometry}
        material={materials.Material}
        position={[0.72, 0.8, 0.44]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Screen_2"
        castShadow
        receiveShadow
        geometry={nodes.Screen_2.geometry}
        material={materials['Material.002']}
        position={[1.06, 0.64, 0.53]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Key_Button001"
        castShadow
        receiveShadow
        geometry={nodes.Key_Button001.geometry}
        material={materials.Material}
        position={[1.45, 0.83, 0.44]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        name="Handphone001"
        castShadow
        receiveShadow
        geometry={nodes.Handphone001.geometry}
        material={materials.Material}
        position={[1.06, 0.64, 0.44]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Shape_Search"
        castShadow
        receiveShadow
        geometry={nodes.Shape_Search.geometry}
        material={materials['Material.010']}
        position={[-0.03, 1.84, 0.22]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Shape_Search_2"
        castShadow
        receiveShadow
        geometry={nodes.Shape_Search_2.geometry}
        material={materials['Material.010']}
        position={[1.06, 1.09, 0.56]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Monitor"
        castShadow
        receiveShadow
        geometry={nodes.Monitor.geometry}
        material={materials.Material}
        position={[0, 1.32, -0.03]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Screen"
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials['Material.009']}
        position={[0, 1.32, 0.13]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Shape_3"
        castShadow
        receiveShadow
        geometry={nodes.Shape_3.geometry}
        material={materials['Material.010']}
        position={[-0.69, 0.89, 0.26]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Shape"
        castShadow
        receiveShadow
        geometry={nodes.Shape.geometry}
        material={materials['Material.001']}
        position={[-0.03, 1.43, 0.26]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Shape_2"
        castShadow
        receiveShadow
        geometry={nodes.Shape_2.geometry}
        material={materials['Material.001']}
        position={[1.07, 0.85, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Line_5"
        castShadow
        receiveShadow
        geometry={nodes.Line_5.geometry}
        material={nodes.Line_5.material}
        position={[1.02, 0.86, 0.6]}
      />
      <mesh
        name="Line_6"
        castShadow
        receiveShadow
        geometry={nodes.Line_6.geometry}
        material={nodes.Line_6.material}
        position={[1.02, 0.8, 0.6]}
      />
      <mesh
        name="Shape_4"
        castShadow
        receiveShadow
        geometry={nodes.Shape_4.geometry}
        material={materials['Material.010']}
        position={[0.9, 0.56, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Shape_5"
        castShadow
        receiveShadow
        geometry={nodes.Shape_5.geometry}
        material={materials['Material.010']}
        position={[0.9, 0.25, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Sun"
        castShadow
        receiveShadow
        geometry={nodes.Sun.geometry}
        material={materials['Material.005']}
        position={[-0.65, 0.97, 0.33]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Mountain"
        castShadow
        receiveShadow
        geometry={nodes.Mountain.geometry}
        material={materials['Material.001']}
        position={[-0.75, 0.88, 0.36]}
      />
      <mesh
        name="Mountain_2"
        castShadow
        receiveShadow
        geometry={nodes.Mountain_2.geometry}
        material={materials['Material.001']}
        position={[-0.59, 0.85, 0.34]}
      />
      <mesh
        name="Sun_2"
        castShadow
        receiveShadow
        geometry={nodes.Sun_2.geometry}
        material={materials['Material.005']}
        position={[0.93, 0.6, 0.6]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Mountain_3"
        castShadow
        receiveShadow
        geometry={nodes.Mountain_3.geometry}
        material={materials['Material.001']}
        position={[0.87, 0.55, 0.61]}
      />
      <mesh
        name="Mountain_4"
        castShadow
        receiveShadow
        geometry={nodes.Mountain_4.geometry}
        material={materials['Material.001']}
        position={[0.95, 0.54, 0.61]}
      />
      <mesh
        name="Play"
        castShadow
        receiveShadow
        geometry={nodes.Play.geometry}
        material={materials['Material.010']}
        position={[-0.15, 0.89, 0.35]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Circle"
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials['Material.005']}
        position={[-0.17, 0.89, 0.3]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Setting"
        castShadow
        receiveShadow
        geometry={nodes.Setting.geometry}
        material={materials['Material.001']}
        position={[0.35, 0.89, 0.32]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Play_2"
        castShadow
        receiveShadow
        geometry={nodes.Play_2.geometry}
        material={materials['Material.003']}
        position={[1.24, 0.55, 0.61]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Circle_2"
        castShadow
        receiveShadow
        geometry={nodes.Circle_2.geometry}
        material={materials['Material.005']}
        position={[1.23, 0.55, 0.58]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Setting_2"
        castShadow
        receiveShadow
        geometry={nodes.Setting_2.geometry}
        material={materials['Material.001']}
        position={[0.9, 0.25, 0.61]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Line"
        castShadow
        receiveShadow
        geometry={nodes.Line.geometry}
        material={nodes.Line.material}
        position={[-0.38, 1.43, 0.32]}
      />
      <mesh
        name="Line_4"
        castShadow
        receiveShadow
        geometry={nodes.Line_4.geometry}
        material={nodes.Line_4.material}
        position={[0.94, 0.91, 0.6]}
      />
      <mesh
        name="Monitor_Holder"
        castShadow
        receiveShadow
        geometry={nodes.Monitor_Holder.geometry}
        material={materials['Material.006']}
        position={[0, 0.41, 0.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Circle001"
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials['Material.009']}
        position={[-0.79, 1.84, 0.27]}
        rotation={[Math.PI / 2, 0.73, 0]}
      />
      <mesh
        name="Circle002"
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials['Material.009']}
        position={[0.85, 1.09, 0.57]}
        rotation={[Math.PI / 2, 0.73, 0]}
      />
    </group>
  )
}

useGLTF.preload('/objects/mobile-monitor.glb')
